events {}

http {
    upstream frontend {
        server eventmanager_frontend:80;
    }

    upstream backend {
        server eventmanager_backend:5000;
    }

    # HTTP
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://frontend;
        }

        location /api {
            proxy_pass http://backend;
        }
    }

    # HTTPS
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            proxy_pass http://frontend;
        }

        location /api {
            proxy_pass http://backend;
        }
    }
}