version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: eventmanager
      MYSQL_USER: eventuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - eventmanager-db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backnet
      - dbnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  backend:
    image: nbouzidia/backend:latest
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://192.168.40.112,https://eventmanager.local
      - CORS_ORIGINS=http://eventmanager.local,https://eventmanager.local,http://192.168.40.112,https://192.168.40.112
      - DB_PORT=3306
      - DB_USER=eventuser
      - DB_PASSWORD_FILE=/run/secrets/mysql_password
      - DB_NAME=eventmanager
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    secrets:
      - mysql_password
      - jwt_secret
    networks:
      - frontnet
      - backnet
    deploy:
      replicas: 2

  frontend:
    image: nbouzidia/frontend:latest
    networks:
      - proxynet
      - frontnet
    deploy:
      replicas: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - proxynet
      - frontnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  proxynet:
    driver: overlay

  frontnet:
    driver: overlay

  backnet:
    driver: overlay
    internal: true

  dbnet:
    driver: overlay
    internal: true

volumes:
  eventmanager-db-data:

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
  jwt_secret:
    external: true